# Generated by Django 4.2 on 2025-08-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
