# Generated by Django 4.2 on 2025-08-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_student_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admission_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="student", name="age", field=models.IntegerField(default=0),
        ),
    ]
